version: '3.3'

volumes:
  static:
  pg_data:
  media:

services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: studygram-back
    build: /backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media/
    expose:
      - 80

  frontend:
    container_name: studygram-front
    build: /frontend
    env_file: .env
    volumes:
      - static:/app/build/

  nginx:
    container_name: studygram-proxy
    build: ./nginx/
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/static/
      - media:/media/
